
CREATE TABLE IF NOT EXISTS library (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  tag TEXT,
  summary TEXT,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
